/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testEntryPointSol from "./TestEntryPoint.sol";
export { TestTarget__factory } from "./TestTarget__factory";
