/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testEntryPointSol from "./TestEntryPoint.sol";
export type { testEntryPointSol };
export type { TestTarget } from "./TestTarget";
