/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestTargetInterface extends Interface {
  getFunction(nameOrSignature: "ping"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Ping"): EventFragment;

  encodeFunctionData(functionFragment: "ping", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;
}

export namespace PingEvent {
  export type InputTuple = [from: AddressLike];
  export type OutputTuple = [from: string];
  export interface OutputObject {
    from: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TestTarget extends BaseContract {
  connect(runner?: ContractRunner | null): TestTarget;
  waitForDeployment(): Promise<this>;

  interface: TestTargetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ping: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ping"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Ping"
  ): TypedContractEvent<
    PingEvent.InputTuple,
    PingEvent.OutputTuple,
    PingEvent.OutputObject
  >;

  filters: {
    "Ping(address)": TypedContractEvent<
      PingEvent.InputTuple,
      PingEvent.OutputTuple,
      PingEvent.OutputObject
    >;
    Ping: TypedContractEvent<
      PingEvent.InputTuple,
      PingEvent.OutputTuple,
      PingEvent.OutputObject
    >;
  };
}
