/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExec,
  IExecInterface,
} from "../../../../src/test/TestEntryPoint.sol/IExec";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IExec__factory {
  static readonly abi = _abi;
  static createInterface(): IExecInterface {
    return new Interface(_abi) as IExecInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IExec {
    return new Contract(address, _abi, runner) as unknown as IExec;
  }
}
